[general]
mac=XX:XX:XX:XX:XX:XX

[soc]
description=State of Charge
unit=%
command=015B
convert_formula=A*100/255

[external_temp]
description=External Temperature
unit=°C
command=22E01B
convert_formula=(A*256+B)/10.0-40.0

[soh]
description=State of Health
unit=%
command=22B061
convert_formula=(A*256+B)/100.0

; You can add other parameters here as you find their PIDs
; [some_other_param]
; description=...
; unit=...
; command=...
; convert_formula=...
