[general]
mac = 00:00:00:00:00:00

[soc]
description = State of Charge
unit = %
command = 015B
equation = val * 100.0 / 255.0

[other_param]
description = Another Parameter
unit = C
command = 221234
equation = (val * 9 / 5) + 32
